"""first

Revision ID: 15afd0c13422
Revises: 
Create Date: 2022-09-22 13:45:20.519488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15afd0c13422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Account', ['id'])
    op.create_unique_constraint(None, 'Currency', ['id'])
    op.create_unique_constraint(None, 'Rating', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Rating', type_='unique')
    op.drop_constraint(None, 'Currency', type_='unique')
    op.drop_constraint(None, 'Account', type_='unique')
    # ### end Alembic commands ###
