"""second

Revision ID: 4b6033d1e876
Revises: 15afd0c13422
Create Date: 2022-09-22 18:03:48.743689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6033d1e876'
down_revision = '15afd0c13422'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
