"""fourt

Revision ID: 754c0797cb1d
Revises: 5855e5f96df7
Create Date: 2022-09-26 12:12:30.068933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754c0797cb1d'
down_revision = '5855e5f96df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
