"""fifth

Revision ID: c34f9a805f26
Revises: 754c0797cb1d
Create Date: 2022-09-26 12:19:29.934018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34f9a805f26'
down_revision = '754c0797cb1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value_to_usd', sa.REAL(), nullable=False),
    sa.Column('available_quantity', sa.REAL(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cur_name', sa.String(length=30), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('trannsaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('type_transaction', sa.String(length=30), nullable=False),
    sa.Column('amount_spent_cur', sa.REAL(), nullable=False),
    sa.Column('amount_received_cur', sa.REAL(), nullable=False),
    sa.Column('currency_transaction_in', sa.String(length=30), nullable=False),
    sa.Column('currency_transaction_from', sa.String(length=30), nullable=False),
    sa.Column('date_time', sa.String(length=30), nullable=False),
    sa.Column('commission', sa.REAL(), nullable=False),
    sa.Column('balance_transaction_in', sa.String(), nullable=False),
    sa.Column('balance_transaction_from', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionQueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Currency')
    op.drop_table('Trannsaction')
    op.drop_table('TransactionQueue')
    op.drop_table('Rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rating',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Rating_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('cur_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Rating_pkey'),
    sa.UniqueConstraint('id', name='Rating_id_key')
    )
    op.create_table('TransactionQueue',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TransactionQueue_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='TransactionQueue_pkey')
    )
    op.create_table('Trannsaction',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Trannsaction_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_transaction', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('amount_spent_cur', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('amount_received_cur', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('currency_transaction_in', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('currency_transaction_from', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('date_time', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('commission', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('balance_transaction_in', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('balance_transaction_from', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Trannsaction_pkey')
    )
    op.create_table('Currency',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Currency_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('value_to_usd', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('available_quantity', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Currency_pkey'),
    sa.UniqueConstraint('id', name='Currency_id_key')
    )
    op.drop_table('transactionQueue')
    op.drop_table('trannsaction')
    op.drop_table('rating')
    op.drop_table('currency')
    # ### end Alembic commands ###
